spool logs\br_create.log

DROP SEQUENCE BR_IDBR_SEQ;
CREATE SEQUENCE  BR_IDBR_SEQ  
  MINVALUE 1000 MAXVALUE 999999999999999999999999 INCREMENT BY 1  NOCYCLE ;
  
DROP TABLE BR CASCADE CONSTRAINTS;
CREATE TABLE BR (
  IDBR NUMBER(11,0) NOT NULL,
  IDKAM NUMBER(11,0),
  IDRep VARCHAR2(255),
  IDClient NUMBER(11,0),
  IDProd NUMBER(11,0),
  Packs NUMBER(5,0) DEFAULT 0,
  IDHY NUMBER(11,0)
);

ALTER TABLE BR
ADD CONSTRAINT PK_BR PRIMARY KEY
(
  IDBR
)
ENABLE
;

CREATE INDEX BRIDRep ON BR
(
  IDRep
)
;

spool off;

exit;



