spool logs\busunits_create.log

DROP SEQUENCE BusUnits_IDBusUnit_SEQ;
CREATE SEQUENCE  BusUnits_IDBusUnit_SEQ  
  MINVALUE 10 MAXVALUE 999999999999999999999999 INCREMENT BY 1  NOCYCLE ;

DROP TABLE BusUnits CASCADE CONSTRAINTS;

CREATE TABLE BusUnits (
  IDBusUnit NUMBER(11,0) NOT NULL,
  BusUnit VARCHAR2(255)
); 

ALTER TABLE BusUnits
ADD CONSTRAINT PK_BusUnits PRIMARY KEY
(
  IDBusUnit
)
ENABLE;

spool off;

exit;

