spool logs\clients_create.log

DROP SEQUENCE Clients_IDClient_SEQ;
CREATE SEQUENCE  Clients_IDClient_SEQ  
  MINVALUE 1000 MAXVALUE 999999999999999999999999 INCREMENT BY 1  NOCYCLE ;
  
DROP TABLE Clients CASCADE CONSTRAINTS;

CREATE TABLE Clients (
  IDClient NUMBER(11,0) NOT NULL,
  Client VARCHAR2(1024),
  City VARCHAR2(255),
  IDReg NUMBER(11,0)
);

ALTER TABLE Clients
ADD CONSTRAINT PK_Clients PRIMARY KEY
(
  IDClient
)
ENABLE
;

spool off


exit;
