--------------------------------------------------------
--  File created - понедельник-Август-01-2011   
--------------------------------------------------------
delete from clients;
Insert into Clients (IDClient,Client,City,IDReg) values (1,'ГУЗ "Самарский областной онкологический диспансер"','Самара',57);
Insert into Clients (IDClient,Client,City,IDReg) values (2,'ГУЗ “Самарская областная клиническая больница им. М.И. Калинина”','Самара',57);
Insert into Clients (IDClient,Client,City,IDReg) values (3,'Клиники Самарского государственного университета','Самара',57);
Insert into Clients (IDClient,Client,City,IDReg) values (4,'ММУ «Городская клиническая больница №1 имени. Н.И. Пирогова»','Самара',57);
Insert into Clients (IDClient,Client,City,IDReg) values (5,'ФГОУ ВПО "Самарский военно-медицинский институт" МО РФ','Самара',57);
Insert into Clients (IDClient,Client,City,IDReg) values (6,'ММУ "Детская городская клиническая больница № 1 им. Н.Н. Ивановой"','Самара',57);
Insert into Clients (IDClient,Client,City,IDReg) values (7,'МУЗ "Городская клиническая больница №5 МедВАЗ"','Тольятти',57);
Insert into Clients (IDClient,Client,City,IDReg) values (8,'МУЗ "Городская клиническая больница №1"','Тольятти',57);
Insert into Clients (IDClient,Client,City,IDReg) values (9,'Городской онкологический диспансер','Сызрань',57);
Insert into Clients (IDClient,Client,City,IDReg) values (10,'Центральная городская больница','Новокуйбышевск',57);
Insert into Clients (IDClient,Client,City,IDReg) values (11,'Центр диализа "Fresenius Medical Care"','Ульяновск',74);
Insert into Clients (IDClient,Client,City,IDReg) values (12,'Областной онкологический диспансер','Ульяновск',74);
Insert into Clients (IDClient,Client,City,IDReg) values (13,'ГУЗ "Оренбургский областной клинический онкологический диспансер"','Оренбург',49);
Insert into Clients (IDClient,Client,City,IDReg) values (14,'ГУЗ "Оренбургский областной центр по профилактике и борьбе со СПИД и инфекционными заболеваниями"','Оренбург',49);
Insert into Clients (IDClient,Client,City,IDReg) values (15,'ММУЗ "ГКБ СМП №1"','Оренбург',49);
Insert into Clients (IDClient,Client,City,IDReg) values (16,'МУЗ "Орский городской онкологический диспансер"','Орск',49);
Insert into Clients (IDClient,Client,City,IDReg) values (17,'МЛПУ "Городская больница №1"','Орск',49);
Insert into Clients (IDClient,Client,City,IDReg) values (18,'МУЗ "Городская больница №1"','Новотроицк',49);
Insert into Clients (IDClient,Client,City,IDReg) values (19,'МУЗ "Городская больница №1"','Бузулук',49);
Insert into Clients (IDClient,Client,City,IDReg) values (20,'ГУЗ "Башкирский республиканский клинический онкологический диспансер"','Уфа',7);
Insert into Clients (IDClient,Client,City,IDReg) values (21,'ГУЗ "Республиканская клиническая больница им. Г.Г. Куватова"','Уфа',7);
Insert into Clients (IDClient,Client,City,IDReg) values (22,'ГУЗ "Республиканский кардиологический диспансер"','Уфа',7);
Insert into Clients (IDClient,Client,City,IDReg) values (23,'Городская больница №13','Уфа',7);
Insert into Clients (IDClient,Client,City,IDReg) values (24,'ГУЗ "Областной онкологический диспансер №1"','Энгельс',59);
Insert into Clients (IDClient,Client,City,IDReg) values (25,'ГУЗ "Саратовский областной онкологический диспансер №2"','Саратов',59);
Insert into Clients (IDClient,Client,City,IDReg) values (26,'ММУ "Саратовский городской онкологический диспансер"','Саратов',59);
Insert into Clients (IDClient,Client,City,IDReg) values (27,'Вольский межрайонный онкологический диспансер','Вольск',59);
Insert into Clients (IDClient,Client,City,IDReg) values (28,'ГУЗ "Саратовская ОКБ с патологоанатомическим центром"','Саратов',59);
Insert into Clients (IDClient,Client,City,IDReg) values (29,'СГМУ "Клиническая больница им. С.Р. Миротворцева" (№3)','Саратов',59);
Insert into Clients (IDClient,Client,City,IDReg) values (30,'Клиника профпатологии и гематологии СГМУ','Саратов',59);
Insert into Clients (IDClient,Client,City,IDReg) values (31,'НУЗ "Дорожная клиническая больница"','Саратов',59);
Insert into Clients (IDClient,Client,City,IDReg) values (32,'Саратовская областная детская клиническая больница','Саратов',59);
Insert into Clients (IDClient,Client,City,IDReg) values (33,'Фрезениус Нефрокеа','Саратов',59);
Insert into Clients (IDClient,Client,City,IDReg) values (34,'МЗ Саратовской области','Саратов',59);
Insert into Clients (IDClient,Client,City,IDReg) values (35,'МК "Гимекс"','Саратов',59);
Insert into Clients (IDClient,Client,City,IDReg) values (36,'ГУЗ "Областной онкологический диспансер"','Пенза',51);
Insert into Clients (IDClient,Client,City,IDReg) values (37,'ГУЗ "Пензенская областная клиническая больница им. Н.Н. Бурденко"','Пенза',51);
Insert into Clients (IDClient,Client,City,IDReg) values (38,'ГУЗ "Пензенская областная детская клиническая больница им. Н.Ф. Филатова"','Пенза',51);
Insert into Clients (IDClient,Client,City,IDReg) values (39,'Министерство здравоохранения и социального развития Пензенской области','Пенза',51);
Insert into Clients (IDClient,Client,City,IDReg) values (40,'ОАО "Фармация"','Пенза',51);
Insert into Clients (IDClient,Client,City,IDReg) values (41,'ФГУ "Федеральный центр сердечно-сосудистой хирургии Федерального агентства по здравоохранению и социальному развитию"','Пенза',51);
Insert into Clients (IDClient,Client,City,IDReg) values (42,'Городская клиническая больница №1','Балаково',59);
Insert into Clients (IDClient,Client,City,IDReg) values (43,'Медикосанитарная часть ФМБА №156','Балаково',59);
Insert into Clients (IDClient,Client,City,IDReg) values (44,'ГУЗ "Детская республиканская клиническая больница №2"','Саранск',40);
Insert into Clients (IDClient,Client,City,IDReg) values (45,'Городская клиническая больница №4','Саранск',40);
Insert into Clients (IDClient,Client,City,IDReg) values (46,'Мордовская республиканская клиническая больница','Саранск',40);
Insert into Clients (IDClient,Client,City,IDReg) values (47,'Республиканский онкологический диспансер','Саранск',40);
Insert into Clients (IDClient,Client,City,IDReg) values (48,'ГУЗ "Республиканский клинический онкологический диспансер"','Казань',67);
Insert into Clients (IDClient,Client,City,IDReg) values (49,'МУЗ "Городская клиническая больница №16"','Казань',67);
Insert into Clients (IDClient,Client,City,IDReg) values (50,'МУЗ "Республиканская детская клиническая больница"','Казань',67);
Insert into Clients (IDClient,Client,City,IDReg) values (51,'МУЗ "Больница скорой медицинской помощи №2"','Казань',67);
Insert into Clients (IDClient,Client,City,IDReg) values (52,'ГУЗ "Волгоградский областной уронефрологический центр"','Волжский',12);
Insert into Clients (IDClient,Client,City,IDReg) values (53,'ГУЗ "Волгоградский областной клинический онкологический диспансер"','Волгоград',12);
Insert into Clients (IDClient,Client,City,IDReg) values (54,'Онкологический диспансер №2','Волжский',12);
Insert into Clients (IDClient,Client,City,IDReg) values (55,'Онкологический диспансер №3','Камышин',12);
Insert into Clients (IDClient,Client,City,IDReg) values (56,'ГУЗ "Волгоградская областная клиническая больница №1"','Волгоград',12);
Insert into Clients (IDClient,Client,City,IDReg) values (57,'ММУ "БСМП №15"','Волгоград',12);
Insert into Clients (IDClient,Client,City,IDReg) values (58,'ГУЗ "Астраханский областной клинический онкологический диспансер"','Астрахань',6);
Insert into Clients (IDClient,Client,City,IDReg) values (59,'ГУЗ "Александромариинская областная клиническая больница"','Астрахань',6);
Insert into Clients (IDClient,Client,City,IDReg) values (60,'ООО "Евромедик"','Астрахань',6);
Insert into Clients (IDClient,Client,City,IDReg) values (61,'ГУЗ "Нижегородская областная клиническая больница им. Н.А. Семашко"','Нижний Новгород',45);
Insert into Clients (IDClient,Client,City,IDReg) values (62,'ГУЗ "Нижегородский областной онкологический диспансер"','Нижний Новгород',45);
Insert into Clients (IDClient,Client,City,IDReg) values (63,'ФГУ "Приволжский окружной медицинский центр ФМБА РФ"','Нижний Новгород',45);
Insert into Clients (IDClient,Client,City,IDReg) values (64,'МЛПУ "Городская клиническая больница №33"','Нижний Новгород',45);
Insert into Clients (IDClient,Client,City,IDReg) values (65,'МЛПУ "Городская клиническая больница №12"','Нижний Новгород',45);
Insert into Clients (IDClient,Client,City,IDReg) values (66,'ГУ "Нижегородская областная детская клиническая больница"','Нижний Новгород',45);
Insert into Clients (IDClient,Client,City,IDReg) values (67,'МУЗ "Выксунская центральная районная больница"','Выкса',45);
Insert into Clients (IDClient,Client,City,IDReg) values (68,'ГУЗ "Республиканская клиническая больница"','Казань',67);
Insert into Clients (IDClient,Client,City,IDReg) values (69,'МУЗ "Городской онкологический диспансер"','Казань',67);
Insert into Clients (IDClient,Client,City,IDReg) values (73,'МУЗ "Городская детская больница №1"','Казань',67);
Insert into Clients (IDClient,Client,City,IDReg) values (74,'ФГУ "Кировский НИИ Гематологии и Переливания крови ФМБА РФ"','Киров',29);
Insert into Clients (IDClient,Client,City,IDReg) values (75,'ГЛПУ "Кировская областная клиническая больница"','Киров',29);
Insert into Clients (IDClient,Client,City,IDReg) values (76,'ГЛПУ "Кировский областной клинический онкологический диспансер"','Киров',29);
Insert into Clients (IDClient,Client,City,IDReg) values (77,'ГУЗ "Республиканская клиническая больница"','Чебоксары',81);
Insert into Clients (IDClient,Client,City,IDReg) values (78,'ГУЗ "Чувашский республиканский клинический онкологический диспансер"','Чебоксары',81);
Insert into Clients (IDClient,Client,City,IDReg) values (79,'ГУЗ "Республиканская детская клиническая больница"','Чебоксары',81);
Insert into Clients (IDClient,Client,City,IDReg) values (80,'ГУЗ "Первая Республиканская клиническая больница МЗ УР"','Ижевск',73);
Insert into Clients (IDClient,Client,City,IDReg) values (81,'ГУЗ "Удмуртский республиканский клинический онкологический диспансер"','Ижевск',73);
Insert into Clients (IDClient,Client,City,IDReg) values (82,'ГУЗ "Республиканская детская клиническая больница"','Ижевск',73);
Insert into Clients (IDClient,Client,City,IDReg) values (83,'ГОУ ВПО РостГМУ Росздрава','Ростов-на-Дону',55);
Insert into Clients (IDClient,Client,City,IDReg) values (84,'ФГУ "ЮОМЦ ФМБА России"','Ростов-на-Дону',55);
Insert into Clients (IDClient,Client,City,IDReg) values (85,'ГУЗ "Областная больница №2"','Ростов-на-Дону',55);
Insert into Clients (IDClient,Client,City,IDReg) values (86,'ГУЗ "Ростовская областная клиническая больница"','Ростов-на-Дону',55);
Insert into Clients (IDClient,Client,City,IDReg) values (87,'ФГУ "Ростовский Научно-Исследовательский Онкологический Институт МЗ РФ"','Ростов-на-Дону',55);
Insert into Clients (IDClient,Client,City,IDReg) values (88,'ГОУЗ "Онкологический диспансер" РО','Ростов-на-Дону',55);
Insert into Clients (IDClient,Client,City,IDReg) values (89,'Окружной военный клинический госпиталь СКВО 1602','Ростов-на-Дону',55);
Insert into Clients (IDClient,Client,City,IDReg) values (90,'ГУЗ "Госпиталь ветеранов войн РО"','Ростов-на-Дону',55);
Insert into Clients (IDClient,Client,City,IDReg) values (91,'МЛПУ "Городская больница скорой медицинской помощи"','Ростов-на-Дону',55);
Insert into Clients (IDClient,Client,City,IDReg) values (92,'МЛПУЗ "Городская больница №1 им. Н.А. Семашко"','Ростов-на-Дону',55);
Insert into Clients (IDClient,Client,City,IDReg) values (93,'МЛПУЗ "Городская больница №20"','Ростов-на-Дону',55);
Insert into Clients (IDClient,Client,City,IDReg) values (94,'МЛПУЗ "Городская больница №4"','Ростов-на-Дону',55);
Insert into Clients (IDClient,Client,City,IDReg) values (95,'МЛПУЗ "Городская больница №6"','Ростов-на-Дону',55);
Insert into Clients (IDClient,Client,City,IDReg) values (96,'МЛПУЗ "Городская больница №7"','Ростов-на-Дону',55);
Insert into Clients (IDClient,Client,City,IDReg) values (97,'МЛПУЗ "Городская больница №8"','Ростов-на-Дону',55);
Insert into Clients (IDClient,Client,City,IDReg) values (98,'МЛПУЗ "Детская городская больница №1"','Ростов-на-Дону',55);
Insert into Clients (IDClient,Client,City,IDReg) values (99,'МЛПУЗ "Детская городская больница №2"','Ростов-на-Дону',55);
Insert into Clients (IDClient,Client,City,IDReg) values (100,'НУЗ "Дорожная клиническая больн ица на ст. Ростов-главный ОАО РЖД"','Ростов-на-Дону',55);
Insert into Clients (IDClient,Client,City,IDReg) values (101,'ГУЗ "Областная детская больница"','Ростов-на-Дону',55);
Insert into Clients (IDClient,Client,City,IDReg) values (102,'ГУЗ "Детская краевая клиническая больница"','Краснодар',32);
Insert into Clients (IDClient,Client,City,IDReg) values (103,'ГУЗ "Краевой клинический онкологический диспансер"','Краснодар',32);
Insert into Clients (IDClient,Client,City,IDReg) values (104,'ГУЗ "Краснодарская краевая клиническая больница №1 им. С.В. Очаповского"','Краснодар',32);
Insert into Clients (IDClient,Client,City,IDReg) values (105,'ООО "Краевой нефрологический центр"','Краснодар',32);
Insert into Clients (IDClient,Client,City,IDReg) values (106,'ГУЗ "Клинический госпиталь для ветеранов войн"','Краснодар',32);
Insert into Clients (IDClient,Client,City,IDReg) values (107,'ГУЗ "Краевая больница №3"','Краснодар',32);
Insert into Clients (IDClient,Client,City,IDReg) values (108,'МУЗ "Городская больница №2" (КМЛДО)','Краснодар',32);
Insert into Clients (IDClient,Client,City,IDReg) values (109,'МУЗ "Городская больница №4"','Краснодар',32);
Insert into Clients (IDClient,Client,City,IDReg) values (110,'МУЗ "Городская клиническая больница №1"','Краснодар',32);
Insert into Clients (IDClient,Client,City,IDReg) values (111,'МУЗ "Городская клиническая больница №3"','Краснодар',32);
Insert into Clients (IDClient,Client,City,IDReg) values (112,'ГУЗ "Ставропольский краевой клинический онкологический диспансер"','Ставрополь',65);
Insert into Clients (IDClient,Client,City,IDReg) values (113,'ГУЗ "Медицинский центр амбулаторного диализа"','Ставрополь',65);
Insert into Clients (IDClient,Client,City,IDReg) values (114,'ГУЗ "Пятигорский онкологический диспансер"','Пятигорск',65);
Insert into Clients (IDClient,Client,City,IDReg) values (115,'ГУЗ "Краевой эндокринологический диспансер"','Ставрополь',65);
Insert into Clients (IDClient,Client,City,IDReg) values (116,'ГУЗ "Краевая клиническая детская больница"','Ставрополь',65);
Insert into Clients (IDClient,Client,City,IDReg) values (117,'МУЗ "Городская клиническая больница №4"','Ставрополь',65);
Insert into Clients (IDClient,Client,City,IDReg) values (118,'ГУ "Адыгейский республиканский клинический онкологический диспансер"','Майкоп',1);
Insert into Clients (IDClient,Client,City,IDReg) values (119,'Адыгейская республиканская клиническая больница','Майкоп',1);
Insert into Clients (IDClient,Client,City,IDReg) values (120,'Адыгейская республиканская детская клиническая больница','Майкоп',1);
Insert into Clients (IDClient,Client,City,IDReg) values (121,'ООО  "Диализный центр Адыгеи"','Майкоп',1);
Insert into Clients (IDClient,Client,City,IDReg) values (122,'ГУЗ "Республиканская клиническая больница" МЗ КБР','Нальчик',21);
Insert into Clients (IDClient,Client,City,IDReg) values (123,'ГУЗ "Республиканская клиническая больница"','Нальчик',21);
Insert into Clients (IDClient,Client,City,IDReg) values (124,'ГУЗ "Кабардино-Балкарский республиканский онкологический диспансер"','Нальчик',21);
Insert into Clients (IDClient,Client,City,IDReg) values (125,'Республиканская клиническая больница','Черкесск',26);
Insert into Clients (IDClient,Client,City,IDReg) values (126,'Республиканский онкологический диспансер','Черкесск',26);
Insert into Clients (IDClient,Client,City,IDReg) values (127,'Филиал диализного центра ООО "ЭМСИПИ Медикейер"','Черкесск',26);
Insert into Clients (IDClient,Client,City,IDReg) values (128,'БУ ХМАО-Югры "Сургутская окружная клиническая больница"','Сургут',77);
Insert into Clients (IDClient,Client,City,IDReg) values (129,'ГУЗ ХМАО "Окружная клиническая больница"','Ханты-Мансийск',77);
Insert into Clients (IDClient,Client,City,IDReg) values (130,'БУ ХМАО – Югры "Окружная клиническая детская больница"','Нижневартовск',77);
Insert into Clients (IDClient,Client,City,IDReg) values (131,'МУЗ "Нижневартовский онкологический диспансер"','Нижневартовск',77);
Insert into Clients (IDClient,Client,City,IDReg) values (132,'У ХМАО-Югры "Няганская окружная больница"','Нягань',77);
Insert into Clients (IDClient,Client,City,IDReg) values (133,'ГЛПУ "Тюменская областная клиническая больница"','Тюмень',72);
Insert into Clients (IDClient,Client,City,IDReg) values (134,'Областная клиническсая больница №3','Тобольск',72);
Insert into Clients (IDClient,Client,City,IDReg) values (135,'ГЛПУ "Тюменский областной онкологический диспансер"','Тюмень',72);
Insert into Clients (IDClient,Client,City,IDReg) values (136,'ГУЗ "Салехардская окружная клиническая больница"','Салехард',83);
Insert into Clients (IDClient,Client,City,IDReg) values (137,'ГУЗ Ноябрьская окружная клиническая больница','Ноябрьск',83);
Insert into Clients (IDClient,Client,City,IDReg) values (138,'ГУЗ "Новоуренгойская клиническая больница"','Новый Уренгой',83);
Insert into Clients (IDClient,Client,City,IDReg) values (139,'ГУЗ Надымская клиническая больница','Надым',83);
Insert into Clients (IDClient,Client,City,IDReg) values (140,'ГУЗОО "Областная клиническая больница"','Омск',48);
Insert into Clients (IDClient,Client,City,IDReg) values (141,'ГУЗОО "Городская  клиническая больница №1 им. Кабанова А.Н."','Омск',48);
Insert into Clients (IDClient,Client,City,IDReg) values (142,'БУЗОО Областной онкологический диспансер','Омск',48);
Insert into Clients (IDClient,Client,City,IDReg) values (143,'Медицинский центр "ФЕЗФАРМ"','Омск',48);
Insert into Clients (IDClient,Client,City,IDReg) values (144,'Госпиталь для ветеранов войн №2 ДЗ г. Москвы','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (145,'Городская клиническая больница им. С.П. Боткина','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (146,'Городская клиническая больница №20','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (147,'Городская клиническая больница №24','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (148,'Городская клиническая больница №50','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (149,'Городская клиническая больница №52','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (150,'Городская клиническая больница №7','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (151,'Городская клиническая больница №1','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (152,'ООО "Фесфарм"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (153,'ООО "Евромедика"','Красногорск',42);
Insert into Clients (IDClient,Client,City,IDReg) values (154,'Измайловская детская городская клиническая больница','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (155,'ГУЗ "Детская ГКБ Св. Владимира"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (156,'ГУ "МОНИКИ им. М. Ф. Владимирского"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (157,'НИИ скорой помощи им. Н.В. Склифосовского ДЗ г. Москвы','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (158,'ГУЗ МО "Областной онкологический диспансер"','Балашиха',42);
Insert into Clients (IDClient,Client,City,IDReg) values (159,'Эндокринологический диспансер ДЗ г. Москвы','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (160,'ФГУЗ «Клиническая больница №83 ФМБА России»','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (161,'МСЧ №119 ФМБА','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (162,'ФГУ "ГВКГ им. акад. Н.Н. Бурденко" МО РФ','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (163,'ГУЗ "Клинический госпиталь МЧС ГУВД"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (164,'Главный клинический госпиталь МВД РФ','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (165,'МУ "Поликлиника ОАО "Газпром"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (166,'ФГУ "ЛРЦ Росздрава"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (167,'ГОУ ВПО "ММА им. И. М. Сеченова"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (168,'МЦ "Центробанк"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (169,'Государственный научный центр колопроктологии Росмедтехнологий','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (170,'ФГУ Эндокринологический научный центр Росмедтехнологий','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (171,'ФГУ "МНИОИ им. П.А. Герцена Росздрава"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (172,'ФГУ "Российский научный центр рентгенорадиологии Росздрава"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (173,'ФГУ "НИИТ и ИО Росмедтехнологий"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (174,'ФГУ "НИИ урологии Росмедтехнологий"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (175,'ФГУ "Научно-клинический центр детской гематологии, онкологии и иммунологии МЗ РФ"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (176,'ФГУ "НМХЦ им. Н.И. Пирогова Росздрава"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (177,'ГУ "РНЦХ им. акад. Б.В. Петровского РАМН"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (178,'ГУ "РОНЦ им. Н.Н. Блохина РАМН"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (179,'ФГУ "ЦКБ УДП РФ"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (180,'ГУ "ГНЦ РАМН"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (181,'НУЗ ЦКБ №1 ОАО РЖД','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (182,'НУЗ ЦКБ №2 ОАО РЖД','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (183,'ГУ "ЦВКГ ФСБ РФ"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (184,'ФГУ "ФМБЦ им. А.И. Бурназяна ФМБА России"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (185,'ФГУ "РДКБ Минздравсоцразвития России"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (186,'ГУЗ "МГ Клиническая онкологическая больница №62"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (187,'Городская клиническая больница №57','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (188,'Городская клиническая больница №33 им. А.А. Остроумова','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (189,'Городская клиническая больница №40','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (190,'Городская клиническая больница №81','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (191,'Городская клиническая больница №60','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (192,'ГУЗ "Воронежский областной онкологический диспансер"','Воронеж',14);
Insert into Clients (IDClient,Client,City,IDReg) values (193,'ГУЗ "Липецкий областной онкологический диспансер"','Липецк',37);
Insert into Clients (IDClient,Client,City,IDReg) values (194,'ГУЗ "Белгородский областной онкологический диспансер"','Белгород',8);
Insert into Clients (IDClient,Client,City,IDReg) values (195,'ГУЗ "Владимирский областной онкологический диспансер"','Владимир',11);
Insert into Clients (IDClient,Client,City,IDReg) values (196,'ГУЗ "Ивановский областной онкологический диспансер"','Иваново',18);
Insert into Clients (IDClient,Client,City,IDReg) values (197,'ГУЗ "Калужский областной онкологический диспансер"','Калуга',24);
Insert into Clients (IDClient,Client,City,IDReg) values (198,'ГУЗ "Костромской областной онкологический диспансер"','Кострома',31);
Insert into Clients (IDClient,Client,City,IDReg) values (199,'ФГУ "МРНЦ РАМН"','Обнинск',42);
Insert into Clients (IDClient,Client,City,IDReg) values (200,'ГУЗ "Тульский областной онкологический диспансер"','Тула',70);
Insert into Clients (IDClient,Client,City,IDReg) values (201,'ГУЗ "Рязанский областной онкологический диспансер"','Рязань',56);
Insert into Clients (IDClient,Client,City,IDReg) values (202,'ОГУЗ "Смоленский областной онкологический клинический диспансер"','Смоленск',64);
Insert into Clients (IDClient,Client,City,IDReg) values (203,'ГУЗ "Брянский областной онкологический диспансер"','Брянск',9);
Insert into Clients (IDClient,Client,City,IDReg) values (204,'ГУЗ "Орловский областной онкологический диспансер"','Орел',50);
Insert into Clients (IDClient,Client,City,IDReg) values (205,'ГУЗ "Ярославский областной онкологический диспансер"','Ярославль',84);
Insert into Clients (IDClient,Client,City,IDReg) values (206,'ГУЗ МО "Люберецкий онкологический диспансер"','Люберцы',42);
Insert into Clients (IDClient,Client,City,IDReg) values (207,'ГУЗ "Белгородская областная клиническая больница Св. Иоасафа"','Белгород',8);
Insert into Clients (IDClient,Client,City,IDReg) values (208,'ГУЗ "Рязанская областная клиническая больница"','Рязань',56);
Insert into Clients (IDClient,Client,City,IDReg) values (209,'ГУЗ ТО "Тульская областная клиническая больница"','Тула',70);
Insert into Clients (IDClient,Client,City,IDReg) values (210,'ГУЗ "Липецкая областная клиническая больница"','Липецк',37);
Insert into Clients (IDClient,Client,City,IDReg) values (211,'ГУЗ "Ярославльская областная клиническая больница"','Ярославль',84);
Insert into Clients (IDClient,Client,City,IDReg) values (212,'Ярославльская больница РЖД','Ярославль',84);
Insert into Clients (IDClient,Client,City,IDReg) values (213,'ГУЗ "Воронежская областная клиническая больница №1"','Воронеж',14);
Insert into Clients (IDClient,Client,City,IDReg) values (214,'Костромская областная больница','Кострома',31);
Insert into Clients (IDClient,Client,City,IDReg) values (215,'Медсанчасть "Свободный Сокол"','Липецк',37);
Insert into Clients (IDClient,Client,City,IDReg) values (216,'ГУЗ "Калужская областная больница"','Калуга',24);
Insert into Clients (IDClient,Client,City,IDReg) values (217,'ГБУЗ "Брянская областная больница №1"','Брянск',9);
Insert into Clients (IDClient,Client,City,IDReg) values (218,'Орловская областная больница','Орел',50);
Insert into Clients (IDClient,Client,City,IDReg) values (219,'ГОУ ВПО "Первый МГМУ им. И.М. Сеченова Минздравсоцразвития России"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (220,'ГУЗ "Свердловская областная клиническая больница №1"','Екатеринбург',62);
Insert into Clients (IDClient,Client,City,IDReg) values (221,'ГУ3 "Областная детская клиническая больница №1"','Екатеринбург',62);
Insert into Clients (IDClient,Client,City,IDReg) values (222,'ГУЗ "Cвердловская областная больница №2"','Екатеринбург',62);
Insert into Clients (IDClient,Client,City,IDReg) values (223,'ГБУЗ "Свердловский областной онкологический диспансер"','Екатеринбург',62);
Insert into Clients (IDClient,Client,City,IDReg) values (224,'ГБУЗ СО "Онкологический диспансер №2"','Нижний Тагил',62);
Insert into Clients (IDClient,Client,City,IDReg) values (225,'ГУЗ СО "Онкологический диспансер №3"','Каменск-Уральский',62);
Insert into Clients (IDClient,Client,City,IDReg) values (226,'МУ "Центральная городская больница №7"','Екатеринбург',62);
Insert into Clients (IDClient,Client,City,IDReg) values (227,'МУ "Городская клиническая больница №40"','Екатеринбург',62);
Insert into Clients (IDClient,Client,City,IDReg) values (228,'МУЗ "Центральная городская больница"','Екатеринбург',62);
Insert into Clients (IDClient,Client,City,IDReg) values (229,'МУЗ "Городская больница № 1 г. Асбеста"','Асбест',62);
Insert into Clients (IDClient,Client,City,IDReg) values (230,'МУЗ "Каменская центральная районная больница"','Каменск-Уральский',62);
Insert into Clients (IDClient,Client,City,IDReg) values (231,'ММУ "Ревдинская городская больница"','Ревда',62);
Insert into Clients (IDClient,Client,City,IDReg) values (232,'МУЗ "Городская больница №1"','Екатеринбург',62);
Insert into Clients (IDClient,Client,City,IDReg) values (233,'ГУЗ "Пермская краевая клиническая больница"','Пермь',52);
Insert into Clients (IDClient,Client,City,IDReg) values (234,'ГУЗ "Пермская краевая клиническая больница №3 "Центр диализа"','Пермь',52);
Insert into Clients (IDClient,Client,City,IDReg) values (235,'ГУЗ "Пермский краевой онкологический диспансер"','Пермь',52);
Insert into Clients (IDClient,Client,City,IDReg) values (236,'ГМЛПУЗ "Челябинская областная клиническая больница"','Челябинск',78);
Insert into Clients (IDClient,Client,City,IDReg) values (237,'ГЛПУ "Челябинский областной  клинический онкологический диспансер"','Челябинск',78);
Insert into Clients (IDClient,Client,City,IDReg) values (238,'ГУЗ "Областной онкологический диспансер №2"','Магнитогорск',78);
Insert into Clients (IDClient,Client,City,IDReg) values (239,'ГУЗ "Областной онкологический диспансер №3"','Копейск',78);
Insert into Clients (IDClient,Client,City,IDReg) values (240,'ГБУЗ НСО "Государственная Новосибирская областная клиническая больница" ','Новосибирск',47);
Insert into Clients (IDClient,Client,City,IDReg) values (241,'ГБУЗ НСО "Новосибирский областной онкологический диспансер" ','Новосибирск',47);
Insert into Clients (IDClient,Client,City,IDReg) values (242,'ГУ "Новосибирский НИИ патологии кровообращения имени академика Е.Н. Мешалкина"','Новосибирск',47);
Insert into Clients (IDClient,Client,City,IDReg) values (243,'ГУ "Дорожная клиническая больница"','Новосибирск',47);
Insert into Clients (IDClient,Client,City,IDReg) values (244,'ГУ "НИИ травматологии и ортопедии"','Новосибирск',47);
Insert into Clients (IDClient,Client,City,IDReg) values (245,'МУЗ "Клиническая больница №1"','Новосибирск',47);
Insert into Clients (IDClient,Client,City,IDReg) values (246,'МУЗ "Городская клиническая больница №2"','Новосибирск',47);
Insert into Clients (IDClient,Client,City,IDReg) values (247,'МУЗ "Городская клиническая больница №11"','Новосибирск',47);
Insert into Clients (IDClient,Client,City,IDReg) values (248,'ГУЗ "Краевая клиническая больница"','Барнаул',3);
Insert into Clients (IDClient,Client,City,IDReg) values (249,'МУЗ "Городская больница №8"','Барнаул',3);
Insert into Clients (IDClient,Client,City,IDReg) values (250,'ГУЗ "Алтайский краевой онкологический диспансер"','Барнаул',3);
Insert into Clients (IDClient,Client,City,IDReg) values (251,'ГУЗ "Онкологический диспансер"','Бийск',3);
Insert into Clients (IDClient,Client,City,IDReg) values (252,'ГУЗ "Онкологический диспансер"','Рубцовск',3);
Insert into Clients (IDClient,Client,City,IDReg) values (253,'ГУЗ "Кемеровская областная клиническая больница"','Кемерово',28);
Insert into Clients (IDClient,Client,City,IDReg) values (254,'ГУЗ "Кемеровский областной клинический онкологический диспансер"','Кемерово',28);
Insert into Clients (IDClient,Client,City,IDReg) values (255,'МЛПУ "Городская клиническая больница №1"','Новокузнецк',28);
Insert into Clients (IDClient,Client,City,IDReg) values (256,'МЛПУ "Новокузнецкий городской онкологический диспансер"','Новокузнецк',28);
Insert into Clients (IDClient,Client,City,IDReg) values (257,'ОГУЗ "Томская областная клиническая больница"','Томск',69);
Insert into Clients (IDClient,Client,City,IDReg) values (258,'ОГУЗ "Томский областной онкологический диспансер"','Томск',69);
Insert into Clients (IDClient,Client,City,IDReg) values (259,'ГУ "НИИ Онкологии ТНЦ СО РАМН"','Томск',69);
Insert into Clients (IDClient,Client,City,IDReg) values (260,'ФГУЗ "Клиническая больница №81 ФМБА России"','Северск',69);
Insert into Clients (IDClient,Client,City,IDReg) values (261,'КГУЗ "Красноярская краевая клиническая больница"','Красноярск',33);
Insert into Clients (IDClient,Client,City,IDReg) values (262,'КГУЗ "Красноярский краевой онкологический диспансер"','Красноярск',33);
Insert into Clients (IDClient,Client,City,IDReg) values (263,'ГУЗ "Иркутская областная клиническая больница"','Иркутск',20);
Insert into Clients (IDClient,Client,City,IDReg) values (264,'ГУЗ "Областной онкологический диспансер"','Иркутск',20);
Insert into Clients (IDClient,Client,City,IDReg) values (265,'МУЗ "Медсанчасть ИАПО"','Иркутск',20);
Insert into Clients (IDClient,Client,City,IDReg) values (266,'МУЗ "Ангарский онкологический диспансер"','Ангарск',20);
Insert into Clients (IDClient,Client,City,IDReg) values (267,'МУЗ "Онкологический диспансер"','Братск',20);
Insert into Clients (IDClient,Client,City,IDReg) values (268,'МЛПУ "Онкологический диспансер"','Усолье-Сибирское',20);
Insert into Clients (IDClient,Client,City,IDReg) values (269,'ГУЗ "Краевая клиническая больница № 1 им. проф. Сергеева"','Хабаровск',75);
Insert into Clients (IDClient,Client,City,IDReg) values (270,'ГУЗ "Краевой клинический центр онкологии"','Хабаровск',75);
Insert into Clients (IDClient,Client,City,IDReg) values (271,'ГУЗ "Краевой приморский онкологический диспансер"','Владивосток',53);
Insert into Clients (IDClient,Client,City,IDReg) values (272,'ГУЗ "Краевая клиническая больница №1"','Владивосток',53);
Insert into Clients (IDClient,Client,City,IDReg) values (273,'ГУЗ "Краевая клиническая больница №2"','Владивосток',53);
Insert into Clients (IDClient,Client,City,IDReg) values (274,'МУЗ "Городская клиническая больница №2"','Владивосток',53);
Insert into Clients (IDClient,Client,City,IDReg) values (275,'ГУЗ "Амурская областная клиническая больница"','Благовещенск',4);
Insert into Clients (IDClient,Client,City,IDReg) values (276,'ГУЗ "Амурский областной клинический онкологический диспансер"','Благовещенск',4);
Insert into Clients (IDClient,Client,City,IDReg) values (277,'ГУЗ "Республиканская больница №1" - Национальный центр медицины','Якутск',60);
Insert into Clients (IDClient,Client,City,IDReg) values (278,'ГУЗ "Республиканская больница №2" - Центр экстренной медицинской помощи','Якутск',60);
Insert into Clients (IDClient,Client,City,IDReg) values (279,'ГУЗ "Якутский республиканский онкологический центр"','Якутск',60);
Insert into Clients (IDClient,Client,City,IDReg) values (280,'ГУЗ "Магаданский областной онкологический центр"','Магадан',38);
Insert into Clients (IDClient,Client,City,IDReg) values (281,'ГУЗ "Магаданская областная больница"','Магадан',38);
Insert into Clients (IDClient,Client,City,IDReg) values (282,'ОГУЗ "Сахалинская областная больница"','Южно-Сахалинск',61);
Insert into Clients (IDClient,Client,City,IDReg) values (283,'ГУЗ "Сахалинский областной онкологический диспансер"','Южно-Сахалинск',61);
Insert into Clients (IDClient,Client,City,IDReg) values (284,'ГУЗ "Камчатский краевой онкологический диспансер"','Петропавловск-Камчатский',25);
Insert into Clients (IDClient,Client,City,IDReg) values (285,'ГУЗ "Камчатская областная больница им. А.С. Лукашевского"','Петропавловск-Камчатский',25);
Insert into Clients (IDClient,Client,City,IDReg) values (286,'Главное военно-медицинское управление Минобороны РФ (ГВМУ)','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (287,'ГУЗ "Городская больница №31"','Санкт-Петербург',58);
Insert into Clients (IDClient,Client,City,IDReg) values (288,'ГУЗ "Городской клинический онкологический диспансер"','Санкт-Петербург',58);
Insert into Clients (IDClient,Client,City,IDReg) values (289,'Госпиталь МЧС России','Санкт-Петербург',58);
Insert into Clients (IDClient,Client,City,IDReg) values (290,'ГУЗ "Ленинградская областная клиническая больница"','Санкт-Петербург',58);
Insert into Clients (IDClient,Client,City,IDReg) values (291,'ГОУ ДПО "СПбМАПО"','Санкт-Петербург',58);
Insert into Clients (IDClient,Client,City,IDReg) values (292,'ФГУ "НИИ онкологии имени Н.Н. Петрова"','Санкт-Петербург',58);
Insert into Clients (IDClient,Client,City,IDReg) values (293,'ФГОУВПО "ВМА имени С.М. Кирова"','Санкт-Петербург',58);
Insert into Clients (IDClient,Client,City,IDReg) values (294,'ГУЗ "Николаевская больница"','Санкт-Петербург',58);
Insert into Clients (IDClient,Client,City,IDReg) values (295,'ОГУ "Российский НИИ гематологии и трансфузиологии"','Санкт-Петербург',58);
Insert into Clients (IDClient,Client,City,IDReg) values (296,'ГУ "Северо-западный окружной медицинский центр МЗ РФ"','Санкт-Петербург',58);
Insert into Clients (IDClient,Client,City,IDReg) values (297,'ГОУВПО "СПбГМА им. И.И. Мечникова Росздрава"','Санкт-Петербург',58);
Insert into Clients (IDClient,Client,City,IDReg) values (298,'ГОУВПО "СПбГМУ им. академика И.П. Павлова"','Санкт-Петербург',58);
Insert into Clients (IDClient,Client,City,IDReg) values (299,'ГОУ ВПО "СПбГПМА"','Санкт-Петербург',58);
Insert into Clients (IDClient,Client,City,IDReg) values (300,'ФГУ "Федеральный центр сердца, крови и эндокринологии им. В.А. Алмазова"','Санкт-Петербург',58);
Insert into Clients (IDClient,Client,City,IDReg) values (301,'ФГУ "Российский научный центр радиологии и хирургических технологий Росмедтехнологий"','Санкт-Петербург',58);
Insert into Clients (IDClient,Client,City,IDReg) values (302,'ГУЗ "Архангельский областной клинический онкологический диспансер"','Архангельск',5);
Insert into Clients (IDClient,Client,City,IDReg) values (303,'ФГУ “Северный медицинский клинический центр им. Н.А. Семашко ФМБА России”','Архангельск',5);
Insert into Clients (IDClient,Client,City,IDReg) values (304,'МУЗ "Первая ГКБ скорой медицинской помощи им. Е.Е. Волосевич"','Архангельск',5);
Insert into Clients (IDClient,Client,City,IDReg) values (305,'ГМУ "Областной клинический онкологический диспансер"','Великий Новгород',46);
Insert into Clients (IDClient,Client,City,IDReg) values (306,'ГУЗ "Новгородская областная клиническая больница"','Великий Новгород',46);
Insert into Clients (IDClient,Client,City,IDReg) values (307,'ГУЗ "Вологодская областная больница №1"','Вологда',13);
Insert into Clients (IDClient,Client,City,IDReg) values (308,'ГУЗ "Вологодский областной онкологический диспансер"','Вологда',13);
Insert into Clients (IDClient,Client,City,IDReg) values (309,'ГУЗ «Калининградская областная клиническая больница»','Калининград',22);
Insert into Clients (IDClient,Client,City,IDReg) values (310,'ГУЗ "Республиканская больница им. В.А. Баранова"','Петрозаводск',27);
Insert into Clients (IDClient,Client,City,IDReg) values (311,'ГУЗ "Коми республиканский онкологический диспансер"','Сыктывкар',30);
Insert into Clients (IDClient,Client,City,IDReg) values (312,'ГУ РК "Коми республиканская больница"','Сыктывкар',30);
Insert into Clients (IDClient,Client,City,IDReg) values (313,'ГУЗ "Мурманская областная клиническая больница имени П.А. Баяндина"','Мурманск',43);
Insert into Clients (IDClient,Client,City,IDReg) values (314,'ГУЗ "Мурманский областной онкологический диспансер"','Мурманск',43);
Insert into Clients (IDClient,Client,City,IDReg) values (315,'ГУЗ “Псковский онкологический диспансер”','Псков',54);
Insert into Clients (IDClient,Client,City,IDReg) values (316,'ООО "Фармцентр"','Саратов',59);
Insert into Clients (IDClient,Client,City,IDReg) values (317,'ГУЗ "Областная детская клиническая больница им. Н.Н. Силищевой"','Астрахань',6);
Insert into Clients (IDClient,Client,City,IDReg) values (318,'ФГУ "ФЦССХ Росздрава"','Астрахань',6);
Insert into Clients (IDClient,Client,City,IDReg) values (319,'Управление Федеральной службы исполнения наказаний Астраханской области
Управление Федеральной службы
исполнения наказаний','Астрахань',6);
Insert into Clients (IDClient,Client,City,IDReg) values (320,'НП СОЗГ "Страховая аптека "Народная"','Калининград',22);
Insert into Clients (IDClient,Client,City,IDReg) values (321,'ООО "РЦСЗ Ленмединформ"','Санкт-Петербург',58);
Insert into Clients (IDClient,Client,City,IDReg) values (322,'ГУЗ "Городская больница Св. Елизаветы"','Санкт-Петербург',58);
Insert into Clients (IDClient,Client,City,IDReg) values (323,'ООО "РосФарм"','Ростов-на-Дону',55);
Insert into Clients (IDClient,Client,City,IDReg) values (324,'ГУП АО «Фармация»','Архангельск',5);
Insert into Clients (IDClient,Client,City,IDReg) values (325,'Медицинское учреждение «Детский хоспис»','Санкт-Петербург',58);
Insert into Clients (IDClient,Client,City,IDReg) values (326,'ГУЗ "Городская больница Св. Великомученика Георгия"','Санкт-Петербург',58);
Insert into Clients (IDClient,Client,City,IDReg) values (327,'ФГУ "ЦНИИРРИ"','Санкт-Петербург',58);
Insert into Clients (IDClient,Client,City,IDReg) values (328,'ООО "Алоэ-Фарм"','Архангельск',5);
Insert into Clients (IDClient,Client,City,IDReg) values (329,'ЛОГП "Ленфарм"','Санкт-Петербург',58);
Insert into Clients (IDClient,Client,City,IDReg) values (330,'ОАО "МосФарм"','Санкт-Петербург',58);
Insert into Clients (IDClient,Client,City,IDReg) values (331,'ГУ "Санкт-Петербургский НИИ скорой помощи им. И.И. Джанелидзе"','Санкт-Петербург',58);
Insert into Clients (IDClient,Client,City,IDReg) values (332,'ГУЗ "Ленинградский областной онкологический диспансер"','Санкт-Петербург',58);
Insert into Clients (IDClient,Client,City,IDReg) values (333,'ООО "Оптифарм"','Санкт-Петербург',58);
Insert into Clients (IDClient,Client,City,IDReg) values (334,'ГУЗ "Городская Мариинская Больница"','Санкт-Петербург',58);
Insert into Clients (IDClient,Client,City,IDReg) values (335,'ЗАО "Торгово-промышленное предприятие "Северо-Запад"','Санкт-Петербург',58);
Insert into Clients (IDClient,Client,City,IDReg) values (336,'ГУЗ "Городская больница №15"','Санкт-Петербург',58);
Insert into Clients (IDClient,Client,City,IDReg) values (337,'ГУЗ "Городская больница №26"','Санкт-Петербург',58);
Insert into Clients (IDClient,Client,City,IDReg) values (338,'ГУП РК "Карелфарм"','Петрозаводск',27);
Insert into Clients (IDClient,Client,City,IDReg) values (339,'ООО "БСС"','Санкт-Петербург',58);
Insert into Clients (IDClient,Client,City,IDReg) values (340,'ООО "Ваша Аптека"','Санкт-Петербург',58);
Insert into Clients (IDClient,Client,City,IDReg) values (341,'Аптека ЗАО "Империя-Фарма"','Санкт-Петербург',58);
Insert into Clients (IDClient,Client,City,IDReg) values (342,'ЗАО "Трэдис"','Архангельск',5);
Insert into Clients (IDClient,Client,City,IDReg) values (343,'ЗАО "Фармакор"','Санкт-Петербург',58);
Insert into Clients (IDClient,Client,City,IDReg) values (344,'ЗАО "Лекомед"','Белгород',8);
Insert into Clients (IDClient,Client,City,IDReg) values (345,'ООО "Соби-Фарм"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (346,'МУЗ "ЦГКБ"','Липецк',37);
Insert into Clients (IDClient,Client,City,IDReg) values (347,'ООО "Аптечная сеть "Радуга"','Екатеринбург',62);
Insert into Clients (IDClient,Client,City,IDReg) values (348,'ГУ "ДРКБ им. Н.М. Кураева"','Махачкала',15);
Insert into Clients (IDClient,Client,City,IDReg) values (349,'ЗАО "ЦВ Протек"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (350,'ООО "Мединдустрия"','Ростов-на-Дону',55);
Insert into Clients (IDClient,Client,City,IDReg) values (351,'ФГУ "ННИИТО Росмедтехнологий"','Нижний Новгород',45);
Insert into Clients (IDClient,Client,City,IDReg) values (352,'ООО "Современные медицинские технологии"','Самара',57);
Insert into Clients (IDClient,Client,City,IDReg) values (353,'ГУП КК "Кубаньфармация"','Краснодар',32);
Insert into Clients (IDClient,Client,City,IDReg) values (354,'ООО "Аптека Шуваловская"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (355,'ЗАО «Фармацевт»','Ростов-на-Дону',55);
Insert into Clients (IDClient,Client,City,IDReg) values (356,'ОГУП «Липецкфармация»','Липецк',37);
Insert into Clients (IDClient,Client,City,IDReg) values (357,'ФГУЗ "КБ №6 им. А.И. Бурназяна ФМБА России"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (358,'ЗАО НИПП "Евромед"','Липецк',37);
Insert into Clients (IDClient,Client,City,IDReg) values (359,'ФГУЗ КБ №123 ФМБА России','Одинцово',42);
Insert into Clients (IDClient,Client,City,IDReg) values (360,'ГУ "ЦА №1 МВД России"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (361,'ГУ «Республиканский центр амбулаторного диализа»','Элиста',23);
Insert into Clients (IDClient,Client,City,IDReg) values (362,'ФГУ «7 ЦВКАГ МО РФ»','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (363,'Комитет по здравоохранению Ленинградской области','Санкт-Петербург',58);
Insert into Clients (IDClient,Client,City,IDReg) values (364,'ФГУ "РНИИТО им. Р.Р.Вредена Росмедтехнологий"','Санкт-Петербург',58);
Insert into Clients (IDClient,Client,City,IDReg) values (365,'ГП "Бурятфармация"','Улан-Удэ',10);
Insert into Clients (IDClient,Client,City,IDReg) values (366,'ГУЗ "Волгоградский областной онкологический диспансер №3"','Волжский',12);
Insert into Clients (IDClient,Client,City,IDReg) values (367,'МУЗ "Городская больница №6"','Владимир',11);
Insert into Clients (IDClient,Client,City,IDReg) values (368,'ФГУ «3 ЦВКГ им. А.А. Вишневского Минобороны России»','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (369,'НИИ нейрохирургии им. Академика Н.Н. Бурденко РАМН','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (370,'ФГУ "ГНЦК Росмедтехнологии"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (371,'ГУП "Медицинская техника и фармация Татарстана"','Казань',67);
Insert into Clients (IDClient,Client,City,IDReg) values (372,'ГУ «Медицинский радиологический научный центр РАМН»','Калуга',24);
Insert into Clients (IDClient,Client,City,IDReg) values (373,'ООО "Бизнес-Инвест"','Иркутск',20);
Insert into Clients (IDClient,Client,City,IDReg) values (374,'ГУЗ Воронежской области','Воронеж',14);
Insert into Clients (IDClient,Client,City,IDReg) values (375,'ЧП Подгурский В.А.','Омск',48);
Insert into Clients (IDClient,Client,City,IDReg) values (376,'ГУЗ "Псковская областная больница"','Псков',54);
Insert into Clients (IDClient,Client,City,IDReg) values (377,'ГУ “ЦОБХР МВД России”','Балашиха',42);
Insert into Clients (IDClient,Client,City,IDReg) values (378,'ЗАО ГП «Рифарм»','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (379,'МУ "Центральная городская больница"','Реутов',42);
Insert into Clients (IDClient,Client,City,IDReg) values (380,'ОАО «Управляющая медицинская компания «Нордмедком»','Тюмень',72);
Insert into Clients (IDClient,Client,City,IDReg) values (381,'ФГУЗ «Клиническая больница №122 им. Л.Г. Соколова» ФМБА России','Санкт-Петербург',58);
Insert into Clients (IDClient,Client,City,IDReg) values (382,'ИП Андросова А.В.','Якутск',60);
Insert into Clients (IDClient,Client,City,IDReg) values (383,'ОАО "Хэппи Дэй"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (384,'МУЗ «ЦГКБ»','Жуковский',42);
Insert into Clients (IDClient,Client,City,IDReg) values (385,'ООО «Фармтрейд»','Ставрополь',65);
Insert into Clients (IDClient,Client,City,IDReg) values (386,'Онкологический клинический диспансер № 1','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (387,'ФГУ "25 ЦВКГ РВСН"','Одинцово',42);
Insert into Clients (IDClient,Client,City,IDReg) values (388,'МЛПУ "Красногорская городская больница №3"','Красногорск',42);
Insert into Clients (IDClient,Client,City,IDReg) values (389,'ГУЗ "Областная детская больница"','Липецк',37);
Insert into Clients (IDClient,Client,City,IDReg) values (390,'ОАО «Мособлфармация»','Подольск',42);
Insert into Clients (IDClient,Client,City,IDReg) values (391,'МУЗ «Курская областная клиническая больница»','Курск',35);
Insert into Clients (IDClient,Client,City,IDReg) values (392,'РАМН','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (393,'ООО «РМК»','Санкт-Петербург',58);
Insert into Clients (IDClient,Client,City,IDReg) values (394,'ГП "Калугафармация"','Калуга',24);
Insert into Clients (IDClient,Client,City,IDReg) values (395,'ООО "Самсон-Фарма"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (396,'ООО "Марко-Трейд"','Кемерово',28);
Insert into Clients (IDClient,Client,City,IDReg) values (397,'ГУП ЧР "Фармация"','Чебоксары',81);
Insert into Clients (IDClient,Client,City,IDReg) values (398,'МУП МО "Фармация"','Тула',70);
Insert into Clients (IDClient,Client,City,IDReg) values (399,'ОГУП "Областной аптечный склад"','Челябинск',78);
Insert into Clients (IDClient,Client,City,IDReg) values (400,'МУ ГБ «ЛипецкМед»','Липецк',37);
Insert into Clients (IDClient,Client,City,IDReg) values (401,'ГУП "Столичные аптеки" (льгота нефро)','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (402,'ООО «Фарм-СКД»','Самара',57);
Insert into Clients (IDClient,Client,City,IDReg) values (403,'ООО "Ставропольский аптечный склад"','Ставрополь',65);
Insert into Clients (IDClient,Client,City,IDReg) values (404,'ООО "Фармакор"','Оренбург',49);
Insert into Clients (IDClient,Client,City,IDReg) values (405,'Управление Алтайского края по здравоохранению и фармацевтической деятельности','Барнаул',3);
Insert into Clients (IDClient,Client,City,IDReg) values (406,'ООО "ИЛАН"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (407,'ГП НО "Нижегородская областная фармация"','Нижний Новгород',45);
Insert into Clients (IDClient,Client,City,IDReg) values (408,'ЧП Павлик Л.Н.','Белгород',8);
Insert into Clients (IDClient,Client,City,IDReg) values (409,'ООО «АПН»','Самара',57);
Insert into Clients (IDClient,Client,City,IDReg) values (410,'ГУЗ "Курский областной клинический онкологический диспансер"','Курск',35);
Insert into Clients (IDClient,Client,City,IDReg) values (411,'ООО "Гронингем"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (412,'ООО "Брянскфарм"','Брянск',9);
Insert into Clients (IDClient,Client,City,IDReg) values (413,'ЗАО "Аврора 2000"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (414,'ЗАО "Иммуновак"','Самара',57);
Insert into Clients (IDClient,Client,City,IDReg) values (415,'Аптека ЗАО "Фирма "Евросервис"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (416,'ФГУ «КБ №1» УДП РФ','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (417,'ГУЗ "Оренбургская областная клиническая больница"','Оренбург',49);
Insert into Clients (IDClient,Client,City,IDReg) values (418,'ГУП "Брянскфармация"','Брянск',9);
Insert into Clients (IDClient,Client,City,IDReg) values (419,'ЗАО "СИА Интернейшнл ЛТД"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (420,'МУЗ "Городская клиническая больница №7"','Казань',67);
Insert into Clients (IDClient,Client,City,IDReg) values (421,'ООО "Латис-Торг"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (422,'ООО "Формика"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (423,'ГУЗ "Тамбовская областная клиническая больница"','Тамбов',66);
Insert into Clients (IDClient,Client,City,IDReg) values (424,'ФГУ "ГБ МСЭ по г. Москва"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (425,'МУ "Центральная районная больница Балашихинского района"','Балашиха',42);
Insert into Clients (IDClient,Client,City,IDReg) values (426,'ГУЗ "Областная клиническая больница"','Чита',17);
Insert into Clients (IDClient,Client,City,IDReg) values (427,'ОАО "Фармимэкс"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (428,'ООО "Морон"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (429,'ООО "Кортес Трэвел"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (430,'ФГУ "МНИИ педиатрии и детской хирургии"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (431,'ГОУ ДПО "РМАПО Росздрава"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (432,'ООО "Лабис Фарма"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (433,'ЗАО "ФТК "Время"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (434,'ЗАО "Интерлизинг-Фарм"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (435,'ООО "Биотек"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (436,'ООО "Авеста Фармацевтика"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (437,'ООО "Бадди"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (438,'ЗАО "Ланцет"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (439,'МУЗ "Городская клиническая больница №6"','Казань',67);
Insert into Clients (IDClient,Client,City,IDReg) values (440,'ФГУ МО РФ "25 Центральный военный клинический госпиталь РВСН"','Одинцово',42);
Insert into Clients (IDClient,Client,City,IDReg) values (441,'ФГУП "МБА" УДП РФ','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (442,'ООО "Отечественные лекарства"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (443,'ОГУЗ "Ненецкая окружная больница"','Нарьян-Мар',44);
Insert into Clients (IDClient,Client,City,IDReg) values (444,'МУЗ "Городская больница №1 им. Г.И. Дробышева"','Магнитогорск',78);
Insert into Clients (IDClient,Client,City,IDReg) values (445,'МУЗ "Республиканская клиническая больница"','Владикавказ',63);
Insert into Clients (IDClient,Client,City,IDReg) values (446,'ЗАО "Компания "Интермедсервис"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (448,'МУЗ "Городская больница №2"','Миасс',78);
Insert into Clients (IDClient,Client,City,IDReg) values (449,'МУЗ "Шатурская центральная районная больница"','Шатура',42);
Insert into Clients (IDClient,Client,City,IDReg) values (450,'ООО "Фармос-Анна"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (451,'ООО "Формула Здоровья"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (452,'ОГУЗ "Областная больница"','Биробиджан',16);
Insert into Clients (IDClient,Client,City,IDReg) values (453,'МУЗ "Городская больница №1"','Первоуральск',62);
Insert into Clients (IDClient,Client,City,IDReg) values (454,'ООО "Аптечная сеть Оз"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (455,'ООО "Ригла"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (456,'ООО "Мединфарм"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (457,'Благотворительный фонд "АиФ. Доброе сердце"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (458,'ООО "Белый Лотос"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (459,'ООО "Росмедкомплект"','Реутов',42);
Insert into Clients (IDClient,Client,City,IDReg) values (460,'ЗАО "Фармстор"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (461,'МУЗ "Сызранская центральная городская больница"','Сызрань',57);
Insert into Clients (IDClient,Client,City,IDReg) values (462,'МЛПУ "Когалымская городская больница"','Когалым',72);
Insert into Clients (IDClient,Client,City,IDReg) values (463,'Региональная льгота МО',null,42);
Insert into Clients (IDClient,Client,City,IDReg) values (464,'МУЗ "Центральная районная больница"','Аксай',55);
Insert into Clients (IDClient,Client,City,IDReg) values (465,'ГУЗ "Хакасский республиканский онкологический диспансер"','Абакан',76);
Insert into Clients (IDClient,Client,City,IDReg) values (466,'МЗ Оренбургской области','Оренбург',49);
Insert into Clients (IDClient,Client,City,IDReg) values (467,'Региональная льгота Ульяновской области','Ульяновск',74);
Insert into Clients (IDClient,Client,City,IDReg) values (468,'МЗ Астраханской области','Астрахань',6);
Insert into Clients (IDClient,Client,City,IDReg) values (469,'ГОУ ВПО "Саратовский государственный медицинский университет им. В. И. Разумовского"','Саратов',59);
Insert into Clients (IDClient,Client,City,IDReg) values (470,'ГУЗ "Республиканский онкологический диспансер"','Грозный',79);
Insert into Clients (IDClient,Client,City,IDReg) values (471,'Централизация СПб','Санкт-Петербург',58);
Insert into Clients (IDClient,Client,City,IDReg) values (472,'Льгота СПб','Санкт-Петербург',58);
Insert into Clients (IDClient,Client,City,IDReg) values (473,'Региональная льгота г. Москва','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (474,'МУЗ "Городская больница №1 им. В.В.Успенского"','Тверь',68);
Insert into Clients (IDClient,Client,City,IDReg) values (475,'ГУП "Столичные аптеки" (специфика нефро)','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (476,'ГУП "Столичные аптеки" (онко+гема)','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (477,'ГУЗ "Хакасская республиканская больница им. Г.Я. Ремишевской"','Абакан',76);
Insert into Clients (IDClient,Client,City,IDReg) values (479,'ЗАО "Нордбер-Трансфарм"','Санкт-Петербург',58);
Insert into Clients (IDClient,Client,City,IDReg) values (480,'ГУЗ "Детская городская больница №1"','Санкт-Петербург',58);
Insert into Clients (IDClient,Client,City,IDReg) values (481,'ГУП "Аптека №33"','Санкт-Петербург',58);
Insert into Clients (IDClient,Client,City,IDReg) values (482,'ЗАО "Вилард"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (483,'МУЗ "Химкинская центральная городская больница"','Химки',42);
Insert into Clients (IDClient,Client,City,IDReg) values (484,'ЗАО "Озон"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (485,'ГУЗ "Республиканская клиническая больница"','Грозный',79);
Insert into Clients (IDClient,Client,City,IDReg) values (486,'МУЗ "Динская центральная районная больница"','ст. Динская',32);
Insert into Clients (IDClient,Client,City,IDReg) values (487,'ГУЗ "Республиканский онкологический диспансер"','Петрозаводск',27);
Insert into Clients (IDClient,Client,City,IDReg) values (488,'ОАО "Курская Фармация"','Курск',35);
Insert into Clients (IDClient,Client,City,IDReg) values (489,'МУЗ "ГКБ №8"','Челябинск',78);
Insert into Clients (IDClient,Client,City,IDReg) values (490,'МУП "КГАУ"','Краснодар',32);
Insert into Clients (IDClient,Client,City,IDReg) values (491,'Департамент Здравоохранения г. Москвы','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (492,'МУЗ "Подольская центральная городская больница"','Подольск',42);
Insert into Clients (IDClient,Client,City,IDReg) values (493,'МУП "Анапафармация"','Анапа',32);
Insert into Clients (IDClient,Client,City,IDReg) values (494,'ООО "Фарматор"','Краснодар',32);
Insert into Clients (IDClient,Client,City,IDReg) values (495,'ИП Нестерова Елена Бориславовна','Кемерово',28);
Insert into Clients (IDClient,Client,City,IDReg) values (496,'ООО "Мелисса-Фарм"','Воронеж',14);
Insert into Clients (IDClient,Client,City,IDReg) values (497,'ООО "Биомастер +"','Ростов-на-Дону',55);
Insert into Clients (IDClient,Client,City,IDReg) values (498,'ОАО "Аптечная сеть "Омское лекарство"','Омск',48);
Insert into Clients (IDClient,Client,City,IDReg) values (499,'МУП МО "Межбольничная аптека №489"','Геленджик',32);
Insert into Clients (IDClient,Client,City,IDReg) values (500,'МП "Аптека №300"','Армавир',32);
Insert into Clients (IDClient,Client,City,IDReg) values (501,'ЗАО "Сандал Лтд"','Екатеринбург',62);
Insert into Clients (IDClient,Client,City,IDReg) values (502,'ЗАО "Юропиан Медикал Сентер"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (503,'ЗАО "Полифарм-Тула"','Тула',70);
Insert into Clients (IDClient,Client,City,IDReg) values (504,'ООО "Фирма "Флорес"','Ставрополь',65);
Insert into Clients (IDClient,Client,City,IDReg) values (505,'ЗАО "Айпара-Спб"','Санкт-Петербург',58);
Insert into Clients (IDClient,Client,City,IDReg) values (506,'МП "Аптека №5"','Чита',17);
Insert into Clients (IDClient,Client,City,IDReg) values (507,'ОГУП "Фармация"','Тверь',42);
Insert into Clients (IDClient,Client,City,IDReg) values (508,'ООО "Здоровые Люди Санкт-Петербург МСЦ"','Санкт-Петербург',58);
Insert into Clients (IDClient,Client,City,IDReg) values (509,'РГУП "Фармация"','Владикавказ',63);
Insert into Clients (IDClient,Client,City,IDReg) values (510,'ФГУП "Антидопинговый центр"','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (511,'МП "Центральная районная аптека" Смидовичского МР','п. Смидович',16);
Insert into Clients (IDClient,Client,City,IDReg) values (512,'ООО "ТФК "АрхиМед"','Тюмень',72);
Insert into Clients (IDClient,Client,City,IDReg) values (513,'ООО "Профит-Фарма"','Черкесск',26);
Insert into Clients (IDClient,Client,City,IDReg) values (514,'МУП Каневского района "Фармация"','ст. Каневская',32);
Insert into Clients (IDClient,Client,City,IDReg) values (515,'ООО "Фармакон плюс"','Ижевск',73);
Insert into Clients (IDClient,Client,City,IDReg) values (516,'Управление здравоохранения администрации муниципального образования','Краснодар',32);
Insert into Clients (IDClient,Client,City,IDReg) values (517,'ФГУ "Поликлиника №1" УДП РФ','Москва',41);
Insert into Clients (IDClient,Client,City,IDReg) values (518,'ФГУ "Научно-исследовательский детский ортопедический институт им. Г.И. Турнера" Росмедтехнологий"','Санкт-Петербург',58);
Insert into Clients (IDClient,Client,City,IDReg) values (519,'НО "Фонд "Нижегородский онкологический научный центр"','Нижний Новгород',45);
Insert into Clients (IDClient,Client,City,IDReg) values (520,'ООО "Здравсервис"','Тула',70);
Insert into Clients (IDClient,Client,City,IDReg) values (521,'ООО "Центральная аптека №186"','Краснодар',32);
Insert into Clients (IDClient,Client,City,IDReg) values (522,'ООО "Рифарм Урал"','Челябинск',78);
Insert into Clients (IDClient,Client,City,IDReg) values (523,'Департамент здравоохранения Вологодской области','Вологда',13);
Insert into Clients (IDClient,Client,City,IDReg) values (524,'ГУЗ "Республиканский онкологичексий диспансер"','Владикавказ',63);
Insert into Clients (IDClient,Client,City,IDReg) values (525,'ГУЗ "Республиканский онкологичексий диспансер"','Махачкала',15);
Insert into Clients (IDClient,Client,City,IDReg) values (526,'ГУП КК "Районная аптека №171 Выселковского района"','ст. Выселки',32);
Insert into Clients (IDClient,Client,City,IDReg) values (527,'ГУЗ "Городская больница №40"','Санкт-Петербург',58);

commit;

exit;
