spool logs\import_create.log

DROP SEQUENCE IMPORT_IDIMP_SEQ;
CREATE SEQUENCE  IMPORT_IDIMP_SEQ  
  MINVALUE 1000 MAXVALUE 999999999999999999999999 INCREMENT BY 1  NOCYCLE ;
  
DROP TABLE IMPORT CASCADE CONSTRAINTS;
CREATE TABLE IMPORT (
  IDIMP NUMBER(11,0) NOT NULL,
  IDWS NUMBER(11,0),
  IDPR NUMBER,
  PRODCODE VARCHAR2(255),
  BATCH VARCHAR2(255),
  QTTY NUMBER(5,0),
  IDMONTH NUMBER(11,0),
  DAMAGED varchar2(255),
  REMARKS VARCHAR2(255)
);

ALTER TABLE IMPORT
ADD CONSTRAINT PK_IMPORT PRIMARY KEY
(
  IDIMP
)
ENABLE
;


spool off;

exit;



