DROP SEQUENCE KAMs_IDKAM_SEQ;
CREATE SEQUENCE  KAMs_IDKAM_SEQ  
  MINVALUE 20 MAXVALUE 999999999999999999999999 INCREMENT BY 1  NOCYCLE ;
  
DROP TABLE KAMs CASCADE CONSTRAINTS;

CREATE TABLE KAMs (
  IDKAM NUMBER(11,0) NOT NULL,
  KAM VARCHAR2(255),
  IDSenKAM FLOAT DEFAULT 0
);

ALTER TABLE KAMs
ADD CONSTRAINT PK_KAMs PRIMARY KEY
(
  IDKAM
)
ENABLE
;

CREATE INDEX КАМsIDSenKAM ON KAMs
(
  IDSenKAM
) 
;  

exit;
