spool logs\month_create.log

DROP SEQUENCE Months_IDMonth_SEQ;
CREATE SEQUENCE  Months_IDMonth_SEQ  
  MINVALUE 61 MAXVALUE 999999999999999999999999 INCREMENT BY 1  NOCYCLE ;
  
DROP TABLE Months CASCADE CONSTRAINTS;

CREATE TABLE Months (
  IDMonth NUMBER(11,0) NOT NULL,
  Month DATE,
  IDHY FLOAT DEFAULT 0
);

ALTER TABLE Months
ADD CONSTRAINT PK_Months PRIMARY KEY
(
  IDMonth
)
ENABLE
;

CREATE INDEX MonthsIDQ ON Months
(
  IDHY
) 
;

spool off

exit;

