--------------------------------------------------------
--  File created - вторник-Август-02-2011   
--------------------------------------------------------
delete from  Regs;

Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (1,'Адыгея Республика','Майкоп','Южный',5.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (2,'Алтай Республика','Горно-Алтайск','Сибирский',3.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (3,'Алтайский край','Барнаул','Сибирский',3.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (4,'Амурская область','Благовещенск','Дальневосточный',3.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (5,'Архангельская область','Архангельск','Северо-Западный',2.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (6,'Астраханская область','Астрахань','Южный',1.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (7,'Башкортостан Республика','Уфа','Приволжский',3.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (8,'Белгородская область','Белгород','Центральный',4.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (9,'Брянская область','Брянск','Центральный',4.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (10,'Бурятия Республика','Улан-Удэ','Сибирский',3.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (11,'Владимирская область','Владимир','Центральный',4.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (12,'Волгоградская область','Волгоград','Южный',1.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (13,'Вологодская область','Вологда','Северо-Западный',2.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (14,'Воронежская область','Воронеж','Центральный',4.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (15,'Дагестан Республика','Махачкала','Северо-Кавказский',5.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (16,'Еврейская автономная область','Биробиджан','Дальневосточный',3.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (17,'Забайкальский край','Чита','Сибирский',3.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (18,'Ивановская область','Иваново','Центральный',4.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (19,'Ингушетия Республика','Назрань','Северо-Кавказский',5.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (20,'Иркутская область','Иркутск','Сибирский',3.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (21,'Кабардино-Балкарская Республика','Нальчик','Северо-Кавказский',5.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (22,'Калиниградская область','Калининград','Северо-Западный',2.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (23,'Калмыкия Республика','Элиста','Южный',5.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (24,'Калужская область','Калуга','Центральный',4.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (25,'Камчатский край','Петропавловск-Камчатский','Дальневосточный',3.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (26,'Карачаево-Черкессия Республика','Черкесск','Северо-Кавказский',5.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (27,'Карелия Республика','Петрозаводск','Северо-Западный',2.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (28,'Кемеровская область','Кемерово','Сибирский',3.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (29,'Кировская область','Киров','Приволжский',1.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (30,'Коми Республика','Сыктывкар','Северо-Западный',2.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (31,'Костромская область','Кострома','Центральный',4.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (32,'Краснодарский край','Краснодар','Южный',5.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (33,'Красноярский край','Красноярск','Сибирский',3.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (34,'Курганская область','Курган','Уральский',3.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (35,'Курская область','Курск','Центральный',4.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (36,'Ленинградская область','Санкт-Петербург','Северо-Западный',2.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (37,'Липецкая область','Липецк','Центральный',4.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (38,'Магаданская область','Магадан','Дальневосточный',3.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (39,'Марий Эл Республика','Йошкар-Ола','Приволжский',1.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (40,'Мордовия Республика','Саранск','Приволжский',1.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (41,'Москва','Москва','Центральный',4.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (42,'Московская область','Москва','Центральный',4.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (43,'Мурманская область','Мурманск','Северо-Западный',2.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (44,'Ненецкий автономный округ','Нарьян-Мар','Северо-Западный',2.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (45,'Нижегородская область','Нижний Новгород','Приволжский',1.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (46,'Новгородская область','Новгород','Северо-Западный',2.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (47,'Новосибирская область','Новосибирск','Сибирский',3.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (48,'Омская область','Омск','Сибирский',3.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (49,'Оренбургская область','Оренбург','Приволжский',1.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (50,'Орловская область','Орел','Центральный',4.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (51,'Пензенская область','Пенза','Приволжский',1.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (52,'Пермский край','Пермь','Приволжский',3.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (53,'Приморский край','Владивосток','Дальневосточный',3.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (54,'Псковская область','Псков','Северо-Западный',2.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (55,'Ростовская область','Ростов-на-Дону','Южный',5.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (56,'Рязанская область','Рязань','Центральный',4.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (57,'Самарская область','Самара','Приволжский',1.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (58,'Санкт-Петербург','Санкт-Петербург','Северо-Западный',2.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (59,'Саратовская область','Саратов','Приволжский',1.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (60,'Саха (Якутия) Республика','Якутск','Дальневосточный',3.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (61,'Сахалинская область','Южно-Сахалинск','Дальневосточный',3.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (62,'Свердловская область','Екатеринбург','Уральский',3.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (63,'Северная Осетия-Алания Республика','Владикавказ','Северо-Кавказский',5.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (64,'Смоленская область','Смоленск','Центральный',4.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (65,'Ставропольский край','Ставрополь','Северо-Кавказский',5.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (66,'Тамбовская область','Тамбов','Центральный',4.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (67,'Татарстан Республика','Казань','Приволжский',1.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (68,'Тверская область','Тверь','Центральный',4.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (69,'Томская область','Томск','Сибирский',3.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (70,'Тульская область','Тула','Центральный',4.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (71,'Тыва Республика','Кызыл','Сибирский',3.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (72,'Тюменская область','Тюмень','Уральский',3.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (73,'Удмуртская Республика','Ижевск','Приволжский',3.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (74,'Ульяновская область','Ульяновск','Приволжский',1.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (75,'Хабаровский край','Хабаровск','Дальневосточный',3.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (76,'Хакасия Республика','Абакан','Сибирский',3.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (77,'Ханты-Мансийский автономный округ - Югра','Ханты-Мансийск','Уральский',3.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (78,'Челябинская область','Челябинск','Уральский',3.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (79,'Чеченская республика','Грозный','Северо-Кавказский',5.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (80,'Чеченская Республика','Грозный','Северо-Кавказский',5.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (81,'Чувашская Республика','Чебоксары','Приволжский',1.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (82,'Чукотский автономный округ','Анадырь','Дальневосточный',3.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (83,'Ямало-Ненецкий автономный округ','Салехард','Уральский',3.0);
Insert into Regs (IDReg,Reg,Cap,SubArea,IDArea) values (84,'Ярославская область','Ярославль','Центральный',4.0);

commit;

exit;

