spool logs\reps_create.log

DROP SEQUENCE Reps_IDRep_SEQ;
CREATE SEQUENCE  Reps_IDRep_SEQ  
  MINVALUE 20 MAXVALUE 999999999999999999999999 INCREMENT BY 1  NOCYCLE ;
  
DROP TABLE Reps CASCADE CONSTRAINTS;

CREATE TABLE Reps (
  IDRep NUMBER(11,0) NOT NULL,
  Emp VARCHAR2(255),
  IDBusUnit VARCHAR2(255)
);


ALTER TABLE Reps
ADD CONSTRAINT PK_Reps PRIMARY KEY
(
  IDRep
)
ENABLE
;

CREATE INDEX RepsIDBusUnit ON Reps
(
  IDBusUnit
)
;

spool off

exit;
