DROP SEQUENCE WSs_IDWS_SEQ;
CREATE SEQUENCE  WSs_IDWS_SEQ  
  MINVALUE 5 MAXVALUE 999999999999999999999999 INCREMENT BY 1  NOCYCLE ;

DROP TABLE WSs CASCADE CONSTRAINTS;

CREATE TABLE WSs (
  IDWS NUMBER(11,0) NOT NULL,
  WS VARCHAR2(255)
);

ALTER TABLE WSs
ADD CONSTRAINT PK_WSs PRIMARY KEY
(
  IDWS
)
ENABLE
;

exit;
