spool logs\years_create.log

DROP SEQUENCE Years_IDY_SEQ;
CREATE SEQUENCE  Years_IDY_SEQ  
  MINVALUE 6 MAXVALUE 999999999999999999999999 INCREMENT BY 1  NOCYCLE ;
  
DROP TABLE Years CASCADE CONSTRAINTS;

CREATE TABLE Years (
  IDY NUMBER(11,0) NOT NULL,
  Y NUMBER(11,0)
);


ALTER TABLE Years
ADD CONSTRAINT PK_Years PRIMARY KEY
(
  IDY
)
ENABLE
;

spool off

exit;
